[package]
name = "freq_plotter"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version="4.0.8", features=["derive"]}
eframe = "0.19.0"
egui = "0.19.0"
tracing = "0.1.36"
tracing-subscriber = "0.3.15"
anyhow = "1.0"
serialport = "4.2"
